apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-config
data:
  DB_URL: "jdbc:postgresql://ds-gtbs.postgres.database.azure.com:5432/gtbs_audit?sslmode=require"
  APP_AUDIT_DEFAULT_REGION_ID: "eu-west-1"
